config/routes.rb
SolidusPaypalExpress::Engine.routes.draw do
  post '/paypal', :to => "paypal#express", :as => :paypal_express
  get '/paypal/confirm', :to => "paypal#confirm", :as => :confirm_paypal
  get '/paypal/cancel', :to => "paypal#cancel", :as => :cancel_paypal
  get '/paypal/notify', :to => "paypal#notify", :as => :notify_paypal
end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    # Using :only here so it doesn't redraw those routes
    resources :orders, :only => [] do
      resources :payments, :only => [] do
        member do
          get 'paypal_refund'
          post 'paypal_refund'
        end
      end
    end
  end
end

app/views/spree/admin/payments/source_views/_paypal.html.erb
<fieldset data-hook="paypal">
  <legend align="center"><%= Spree.t(:transaction, :scope => :paypal) %></legend>

  <table class="stock-contents shipment index" data-hook="stock-contents">
    <colgroup>
      <col style="width: 20%;" />
      <col style="width: 25%;" />
      <col style="width: 20%;" />
      <col style="width: 35%;" />
    </colgroup>
    <thead>
      <tr>
        <th><%= Spree.t(:payer_id, :scope => :paypal) %></th>
        <th><%= Spree.t(:token, :scope => :paypal) %></th>
        <th><%= Spree.t(:transaction_id) %></th>
        <th class="<%= "actions" if (payment.source.state != 'refunded') %>">
          <% if payment.source.state == 'refunded' %>
            <%= Spree.t(:state, :scope => :paypal) %>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= payment.source.payer_id %></td>
        <td><%= payment.source.token %></td>
        <td><%= payment.source.transaction_id %></td>
        <td>
          <% if payment.source.state != 'refunded' %>
            <%#= button_link_to Spree.t('actions.refund', scope: :paypal), paypal_refund_admin_order_payment_path(@order, payment), icon: 'money' %>
            <%= link_to "", paypal_refund_admin_order_payment_path(@order, payment), class: "fa fa-reply icon_link with-tip no-text", data_original_title: "Refund" %>
          <% else %>
            <span class="pill pill-payment"><%= payment.source.state.titleize %></span>
            <div class="alpha six columns">
              <dl>
                <dt><%= Spree.t(:refunded_at, :scope => :paypal) %>:</dt>
                <dd><%= pretty_time(payment.source.refunded_at) %></dd>

                <dt><%= Spree.t(:refund_transaction_id, :scope => :paypal) %>:</dt>
                <dd><%= payment.source.refund_transaction_id %></dd>
              </dl>
            </div>            
          <% end %>
        </td>
      </tr>
    </tbody>
    
  </table>

</fieldset>